name: Prod CI


on:
push:
branches: [ "main" ]


jobs:
run-prod:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4


- uses: databricks/setup-cli@main


- name: Run notebook on Databricks (Prod)
uses: databricks/run-notebook@v0
with:
databricks-host: ${{ secrets.DATABRICKS_HOST }}
databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
local-notebook-path: notebooks/example_notebook.py